Repository delta/dalal-street-client, pull requests merged in 2022-02, with the labels that each got.

#62 Create a stream for isMaketOpen
  lib/blocs/auth/login/login_cubit.dart
  lib/blocs/dalal/dalal_bloc.dart
  lib/blocs/dalal/dalal_event.dart
  lib/main.dart
  lib/streams/generators/market_open_generator.dart
  lib/streams/generators/stock_stream_generator.dart
  lib/streams/generators/user_info_generator.dart
  lib/streams/global_streams.dart
Labels: streams

#69 [Fix] stockworth calc in global streams
  lib/models/dynamic_user_info.dart
  lib/streams/generators/stock_stream_generator.dart
  lib/streams/generators/user_info_generator.dart
Labels: streams, bug-fix

#71 [refactor]: simplify list selection cubit
  lib/blocs/list_selection/list_selection_cubit.dart
  lib/blocs/list_selection/list_selection_state.dart
  lib/blocs/list_selection/selectedIndex/selected_index_cubit.dart
  lib/blocs/list_selection/selectedIndex/selected_index_state.dart
  lib/pages/stock_exchange/components/stock_detail.dart
  lib/pages/stock_exchange/components/stock_list_item.dart
  lib/pages/stock_exchange/exchange_page.dart
Labels: refactor

#54 [Add] charts
  lib/blocs/stock_history/history/stock_history_cubit.dart
  lib/blocs/stock_history/history/stock_history_state.dart
  lib/blocs/stock_history/stream/stock_history_stream_cubit.dart
  lib/blocs/stock_history/stream/stock_history_stream_state.dart
  lib/components/graph/chart_type.dart
  lib/components/graph/line_area.dart
  lib/components/graph/stock_chart.dart
  lib/config/log.dart
  lib/models/time_series_data.dart
  lib/pages/company_page/company_page.dart
  lib/pages/company_page/components/company_prices.dart
  lib/pages/home_page.dart
  lib/theme/colors.dart
  lib/utils/resolution_conversion.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#76 [Add] Toast
  lib/main.dart
  lib/models/snackbar/snackbar_props.dart
  lib/models/snackbar/snackbar_type.dart
  lib/navigation/route_generator.dart
  lib/pages/auth/change_password_page.dart
  lib/pages/auth/forgot_password_page.dart
  lib/pages/auth/login_page.dart
  lib/pages/auth/register_page.dart
  lib/pages/auth/verify_phone/enter_otp_page.dart
  lib/pages/auth/verify_phone/enter_phone_page.dart
  lib/pages/company_page/components/trading_bottom_sheet.dart
  lib/pages/daily_challenges/components/challenge_reward.dart
  lib/pages/daily_challenges/single_day_challenges.dart
  lib/pages/mortgage/components/mortgage_bottom_sheet.dart
  lib/pages/mortgage/components/retrieve_bottom_sheet.dart
  lib/pages/referral_page.dart
  lib/pages/stock_exchange/components/exchange_bottom_sheet.dart
  lib/pages/stock_exchange/components/stock_detail.dart
  lib/utils/snackbar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, ui

#84 Subscribe to multiple streams at the same time using Future.wait()
  lib/streams/global_streams.dart
Labels: enhancement

#74 feat:added notifications page
  assets/icon/notification-bell.svg
  assets/icon/notification-icon.svg
  lib/blocs/notification/notifications_cubit.dart
  lib/blocs/notification/notifications_state.dart
  lib/navigation/route_generator.dart
  lib/pages/notifications_page.dart
  lib/utils/iso_to_datetime.dart
  pubspec.lock
  pubspec.yaml
Labels: new page

#85 Feat(shimmer): create util shimmer widgets for different layouts
  lib/components/shimmers/expanded_image_view.dart
  lib/components/shimmers/expanded_text.dart
  lib/components/shimmers/list_image_view.dart
  lib/components/shimmers/text_column.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, ui

#86 [feat] [routing]: add support for proper web routing
  lib/blocs/dalal/dalal_bloc.dart
  lib/blocs/dalal/dalal_state.dart
  lib/main.dart
  lib/models/menu_item.dart
  lib/navigation/dalal_nav_buidler.dart
  lib/navigation/home_routes.dart
  lib/navigation/nav_utils.dart
  lib/navigation/route_generator.dart
  lib/navigation/router.dart
  lib/pages/auth/check_mail_page.dart
  lib/pages/auth/login_page.dart
  lib/pages/auth/register_page.dart
  lib/pages/auth/verify_phone/enter_otp_page.dart
  lib/pages/auth/verify_phone/enter_phone_page.dart
  lib/pages/dalal_home/dalal_bottom_bar.dart
  lib/pages/dalal_home/dalal_home.dart
  lib/pages/dalal_home/dalal_home_bottom_sheet.dart
  lib/pages/dalal_home/dalal_side_drawer.dart
  lib/pages/home_page.dart
  lib/pages/landing_page.dart
  lib/pages/mortgage/mortgage_home.dart
  lib/pages/splash_page.dart
  lib/streams/global_streams.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor, web, routing

#92 [Add][stream] toast
  lib/components/graph/stock_chart.dart
  lib/components/stock_bar.dart
  lib/main.dart
  lib/navigation/dalal_nav_buidler.dart
  lib/utils/stream_snackbar.dart
Labels: streams

#79 Fix: Make user worth details real time
  lib/blocs/portfolio/transactions/portfolio_transactions_cubit.dart
  lib/blocs/portfolio/transactions/portfolio_transactions_state.dart
  lib/pages/portfolio/portfolio_page.dart
  lib/pages/portfolio/portfolio_transactions.dart
  lib/pages/portfolio/portfolio_userworth.dart
Labels: bug-fix

#91 [Feat]: Add Mortgage page and Retrieve page Web
  lib/blocs/mortgage/mortgage_sheet/cubit/mortgage_sheet_cubit.dart
  lib/blocs/mortgage/mortgage_sheet/cubit/mortgage_sheet_state.dart
  lib/blocs/mortgage/retrieve_sheet/retrieve_sheet_cubit.dart
  lib/blocs/mortgage/retrieve_sheet/retrieve_sheet_state.dart
  lib/pages/mortgage/components/mortgage_stock_item.dart
  lib/pages/mortgage/components/mortgage_table.dart
  lib/pages/mortgage/components/retrieve_bottom_sheet.dart
  lib/pages/mortgage/components/retrieve_stock_item.dart
  lib/pages/mortgage/components/retrieve_table.dart
  lib/pages/mortgage/mortgage_home.dart
  lib/pages/mortgage/mortgage_page.dart
  lib/pages/mortgage/retrieve_page.dart
  lib/pages/stock_exchange/components/stock_detail.dart
  lib/pages/stock_exchange/components/stock_exchange_item.dart
  lib/pages/stock_exchange/exchange_page.dart
Labels: ui, web
