Repository delta/dalal-street-client, pull requests merged in 2022-03, with the labels that each got.

#97 [fix] [route]: bug in /company route
  lib/navigation/dalal_nav_buidler.dart
  lib/navigation/home_routes.dart
  lib/navigation/router.dart
  lib/pages/company_page/company_page.dart
  lib/pages/home_page.dart
  lib/pages/mortgage/mortgage_page.dart
  lib/pages/mortgage/retrieve_page.dart
  lib/pages/stock_exchange/exchange_page.dart
  lib/utils/regex_util.dart
  pubspec.lock
  pubspec.yaml
Labels: bug-fix, routing

#100 [feat]: route redirection
  lib/blocs/dalal/dalal_bloc.dart
  lib/navigation/dalal_nav_buidler.dart
  lib/navigation/home_routes.dart
  lib/navigation/router.dart
Labels: enhancement, routing

#95 [Add]: Added Homepage Web UI
  lib/pages/dalal_home/dalal_home.dart
  lib/pages/home_page.dart
Labels: ui, web

#103 [feat] [ui]: change how daily challenges open state is shown in ui
  lib/blocs/daily_challenges/daily_challenges_page_cubit.dart
  lib/blocs/daily_challenges/daily_challenges_page_state.dart
  lib/pages/daily_challenges/components/daily_challenge_item.dart
  lib/pages/daily_challenges/daily_challenges_page.dart
  lib/pages/daily_challenges/single_day_challenges.dart
  lib/streams/transformations.dart
  lib/utils/form_validation_messages.dart
Labels: enhancement, ui

#105 [feat]: form todos and minor bug fixes in auth routes
  lib/components/reactive_password_field.dart
  lib/main.dart
  lib/navigation/dalal_nav_buidler.dart
  lib/navigation/home_routes.dart
  lib/navigation/router.dart
  lib/pages/auth/change_password_page.dart
  lib/pages/auth/forgot_password_page.dart
  lib/pages/auth/login_page.dart
  lib/pages/auth/register_page.dart
  lib/pages/auth/verify_phone/enter_otp_page.dart
  lib/pages/auth/verify_phone/enter_phone_page.dart
Labels: auth, bug-fix, todo

#108 [fix] [ui]: scrolling issue in DailyChallenges
  lib/pages/daily_challenges/single_day_challenges.dart
Labels: ui, bug-fix

#109 [feat] [ui]: sidebar
  lib/components/collapsible_sidebar/collapsible_sidebar.dart
  lib/components/collapsible_sidebar/components/collapsible_avatar.dart
  lib/components/collapsible_sidebar/components/collapsible_container.dart
  lib/components/collapsible_sidebar/components/collapsible_item.dart
  lib/components/collapsible_sidebar/components/collapsible_item_selection.dart
  lib/components/collapsible_sidebar/components/collapsible_item_widget.dart
  lib/constants/icons.dart
  lib/pages/dalal_home/dalal_home.dart
  lib/pages/dalal_home/dalal_side_drawer.dart
  lib/pages/dalal_home/dalal_sidebar.dart
Labels: ui, todo

#122 Logout button
  assets/icon/logout.svg
  lib/components/dialogs/logout_dialog.dart
  lib/constants/icons.dart
  lib/pages/dalal_home/dalal_home.dart
  lib/pages/dalal_home/dalal_sidebar.dart
  lib/pages/home_page.dart
Labels: ui

#125 Error page
  assets/images/error.png
  lib/constants/images.dart
  lib/navigation/components/dalal_error_page.dart
  lib/navigation/components/dalal_nav_buidler.dart
  lib/navigation/router.dart
Labels: routing

#128 [fix]: marketDay 0 error in DailyChallengesPage
  lib/pages/daily_challenges/daily_challenges_page.dart
Labels: bug-fix

#130 Faq Page
  assets/icon/faq.svg
  lib/constants/icons.dart
  lib/faq.dart
  lib/navigation/components/dalal_nav_buidler.dart
  lib/navigation/router.dart
  lib/pages/dalal_home/dalal_home.dart
  lib/pages/faq_page.dart
  pubspec.lock
  pubspec.yaml
Labels: new page

#139 [fix]: change media partners icon
  assets/icon/mobile-ad.svg
  assets/icon/speaker.svg
  lib/constants/icons.dart
  lib/navigation/home_routes.dart
  pubspec.lock
Labels: bug-fix
